language: python

matrix:
  include:
    - sudo: required
      services:
        - docker
      env: PIP=pip
    - os: osx
      language: generic
      env: PIP=pip2

install:
  - $PYTHON -m pip install -r requirements-dev.txt

script:
  - $PIP install cibuildwheel==0.10.0
  - cibuildwheel --output-dir wheelhouse
