language: python

env:
  global:
    - TWINE_USERNAME=andrew.resch

matrix:
  include:
    - sudo: required
      services:
        - docker
      env: PIP=pip
    - os: osx
      language: generic
      env: PIP=pip2

install:
  - $PIP install -r dev-requirements.txt

script:
  - $PIP install cibuildwheel==0.10.0
  - cibuildwheel --output-dir wheelhouse
  - $PIP install twine
  - python -m twine upload wheelhouse/*.whl
